// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb0CTBXKXLjXNja09eeqf2ilKH14_-OXM',
    appId: '1:162051069283:web:25073be31bf4eb18922f56',
    messagingSenderId: '162051069283',
    projectId: 'fir-app-7dafc',
    authDomain: 'fir-app-7dafc.firebaseapp.com',
    storageBucket: 'fir-app-7dafc.appspot.com',
    measurementId: 'G-ZK3MFQCM6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE72ABT9U5t3_33QdGAE7dABbau8GoU-4',
    appId: '1:162051069283:android:ad11c21238af67ce922f56',
    messagingSenderId: '162051069283',
    projectId: 'fir-app-7dafc',
    storageBucket: 'fir-app-7dafc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBehqcZHkJh0H8HtO0OUAASYRHA5Gzv8q0',
    appId: '1:162051069283:ios:edcc13b3fb4f8f11922f56',
    messagingSenderId: '162051069283',
    projectId: 'fir-app-7dafc',
    storageBucket: 'fir-app-7dafc.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBehqcZHkJh0H8HtO0OUAASYRHA5Gzv8q0',
    appId: '1:162051069283:ios:edcc13b3fb4f8f11922f56',
    messagingSenderId: '162051069283',
    projectId: 'fir-app-7dafc',
    storageBucket: 'fir-app-7dafc.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb0CTBXKXLjXNja09eeqf2ilKH14_-OXM',
    appId: '1:162051069283:web:f9abaa9dab9b2c52922f56',
    messagingSenderId: '162051069283',
    projectId: 'fir-app-7dafc',
    authDomain: 'fir-app-7dafc.firebaseapp.com',
    storageBucket: 'fir-app-7dafc.appspot.com',
    measurementId: 'G-ZZQCPSGD1Q',
  );
}
